tasks:
  - init: |
      pip install --pre robotframework-browser
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - dbaeumer.vscode-eslint