tasks:
  - name: prepare
    before: |
      sudo cp -f /workspace/robotframework-browser-advanced-workshop/.vscode/RBCN23.png /usr/share/backgrounds/xfce/xfce-stripes.png
      clear
  - name: install System
    init: |
      python -m pip install --upgrade pip
      pip install --upgrade -r requirements.txt
      pip install --upgrade robotframework
      rfbrowser init
      npx --yes playwright install-deps
  - name: Command
    command: |
      sudo cp -f /workspace/robotframework-browser-advanced-workshop/.vscode/RBCN23.png /usr/share/backgrounds/xfce/xfce-stripes.png
      clear
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    visibility: private
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - bierner.docs-view
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - PKief.material-icon-theme
    - mechatroner.rainbow-csv