/*
* This file is automatically generated and will be overridden when running the build process.
* Generated on: 2/9/2026, 1:25:08 PM
*/

export interface QuizPage {
  id: string;
  name: string;
  quizzes: QuizComponent[];
}

export interface QuizComponent {
  id: string | null;
  name: string;
  src?: string | null;   // <-- new field
}

export const quizPages: QuizPage[] = [];
